"""initial

Revision ID: a34675f173ee
Revises: 
Create Date: 2025-11-09 22:32:44.535721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34675f173ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'capacity')
    op.drop_column('items', 'slot_id')
    op.drop_column('items', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('slot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('boxes', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
